version: "3.8"

networks:
  gs:
    ipam:
      driver: default
      config:
        - subnet: '192.168.5.0/24'

services:
  core-api:
    container_name: "core-api"
    image: victobonetti\globalsolution-core-api:1.0.0
    networks:
      gs:
        ipv4_address: '192.168.5.2'
    ports:
      - "9091:9091"
    depends_on:
      db:
        condition: "service_healthy"

  db:
    image: "postgres:latest"
    user: postgres
    container_name: "postgres"
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      gs:
        ipv4_address: '192.168.5.4'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "gs"]
      interval: 5s
      timeout: 25s
      retries: 5
